from tkinter import *
from random import choice
import time
from tkinter import messagebox

window = Tk()
window.title('Test Your Brain')
window.resizable(0,0)
class menu_utama:
    canvas = Canvas(window, width=1000,height=600,bg="#F4DEB9")
    def tampil_menu(self) :
        self.canvas.pack()
        self.level = Level()
        self.judul = Label(self.canvas,bg="#F4DEB9",text="Test Your Brain",font='Helvetica 40 bold',fg="black")
        self.judul.place(x=500,y=150,anchor="center")
        self.tutup = Button(self.canvas,bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Tutup",fg="#F4DEB9",command=self.EXIT).place(x=847,y=2)
        self.tentang = Button(self.canvas, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Tentang",fg="#F4DEB9",command=self.about).place(x=2,y=2)
        self.go = Button(self.canvas, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Masuk",fg="#F4DEB9",command=self.level.masuk).place(x=500,y=350,anchor="center")
        window.mainloop()
    def EXIT(self):
        window.destroy()
    def about(self):
        self.canvas.pack_forget()
        self.canva = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.canva.pack()
        self.back = Button(self.canva, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.balik1).place(x=2,y=2)
        self.judul = Label(self.canva, text="Tentang",font='Helvetica 35 bold',bg="#F4DEB9").place(x=500,y=100,anchor="center")
        self.isi = Label(self.canva, text="Permainan ini sangat sederhana yaitu hanya menyamakan pola dari susunan kotak yang ditunjukkan sebelum permainan dimulai. untuk menentukan apakah pola sudah sesuai dengan yang telah ditunjukkan player dapat menunggu hingga waktu yang telah ditentukan habis. jika player salah memilih kotak maka permainan akan berakhir",font='Helvetica 18 bold',bg="#F4DEB9").place(x=2,y=200)
    def balik1(self):
        self.canva.pack_forget()
        self.tampil_menu()

class Level (menu_utama):
    level = Canvas(window, width=1000,height=600,bg="#F4DEB9")
    def masuk(self):
        menu_utama.__init__(self)
        menu_utama.canvas.pack_forget()
        self.level.pack()
        self.game = Game()
        self.judul = Label(self.level, text="Pilih Level",font='Helvetica 35 bold',bg="#F4DEB9").place(x=500,y=150,anchor="center")
        self.back = Button(self.level, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.balik2).place(x=2,y=2)
        self.level1 = Button(self.level, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Mudah",fg="#F4DEB9",command=self.game.mudah).place(x=500,y=300,anchor="center")
        self.level2 = Button(self.level, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Sedang",fg="#F4DEB9",command=self.game.sedang).place(x=500,y=370,anchor="center")
        self.level3 = Button(self.level, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Sulit",fg="#F4DEB9",command=self.game.sulit).place(x=500,y=440,anchor="center")
    def balik2(self):
        self.level.pack_forget()
        self.tampil_menu()
class Game (Level):
    game = Canvas(window, width=1000,height=600,bg="#F4DEB9")
    def balik3(self):
        self.game.pack_forget()
        self.masuk()
    def mudah(self):
        self.level.pack_forget()
        self.game = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.game.pack()
        self.a = "easy"
        self.game.create_rectangle(2,100,1000,500,fill="gray",outline="gray")
        self.warna = ["black","red"]
        self.judul = Label(self.game, text="Mudah",font='Helvetica 25 italic',bg="#F4DEB9").place(x=850,y=5)
        self.back = Button(self.game, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.balik3,state="disable").place(x=2,y=2)
        self.l1 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l1.place(x=400,y=200,anchor="center")
        self.l2 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l2.place(x=400,y=300,anchor="center")
        self.l3 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l3.place(x=400,y=400,anchor="center")
        self.l4 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l4.place(x=500,y=200,anchor="center")
        self.l5 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l5.place(x=500,y=300,anchor="center")
        self.l6 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l6.place(x=500,y=400,anchor="center")
        self.l7 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l7.place(x=600,y=200,anchor="center")
        self.l8 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l8.place(x=600,y=300,anchor="center")
        self.l9 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l9.place(x=600,y=400,anchor="center")
        self.mulai(self.a)
    def sedang(self):
        self.level.pack_forget()
        self.game = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.game.pack()
        self.a = "medium"
        self.game.create_rectangle(2,100,1000,500,fill="gray",outline="gray")
        self.warna = ["black","red"]
        self.judul = Label(self.game, text="Sedang",font='Helvetica 25 italic',bg="#F4DEB9").place(x=850,y=5)
        self.back = Button(self.game, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.balik3,state="disable").place(x=2,y=2)
        self.l1 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l1.place(x=225,y=200,anchor="center")
        self.l2 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l2.place(x=225,y=300,anchor="center")
        self.l3 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l3.place(x=225,y=400,anchor="center")
        self.l4 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l4.place(x=325,y=200,anchor="center")
        self.l5 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l5.place(x=325,y=300,anchor="center")
        self.l6 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l6.place(x=325,y=400,anchor="center")
        self.l7 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l7.place(x=425,y=200,anchor="center")
        self.l8 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l8.place(x=425,y=300,anchor="center")
        self.l9 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l9.place(x=425,y=400,anchor="center")
        self.l10 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l10.place(x=525,y=200,anchor="center")
        self.l11 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l11.place(x=525,y=300,anchor="center")
        self.l12 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l12.place(x=525,y=400,anchor="center")
        self.l13 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l13.place(x=625,y=200,anchor="center")
        self.l14 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l14.place(x=625,y=300,anchor="center")
        self.l15 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l15.place(x=625,y=400,anchor="center")
        self.l16 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l16.place(x=725,y=200,anchor="center")
        self.l17 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l17.place(x=725,y=300,anchor="center")
        self.l18 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l18.place(x=725,y=400,anchor="center")
        self.mulai(self.a)
    def sulit(self):
        self.level.pack_forget()
        self.game = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.game.pack()
        self.a = "hard"
        self.game.create_rectangle(2,100,1000,500,fill="gray",outline="gray")
        self.warna = ["black","red"]
        self.judul = Label(self.game, text="Sulit",font='Helvetica 25 italic',bg="#F4DEB9").place(x=880,y=5)
        self.back = Button(self.game, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.balik3,state="disable").place(x=2,y=2)
        self.l1 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l1.place(x=100,y=200,anchor="center")
        self.l2 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l2.place(x=100,y=300,anchor="center")
        self.l3 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l3.place(x=100,y=400,anchor="center")
        self.l4 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l4.place(x=200,y=200,anchor="center")
        self.l5 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l5.place(x=200,y=300,anchor="center")
        self.l6 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l6.place(x=200,y=400,anchor="center")
        self.l7 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l7.place(x=300,y=200,anchor="center")
        self.l8 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l8.place(x=300,y=300,anchor="center")
        self.l9 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l9.place(x=300,y=400,anchor="center")
        self.l10 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l10.place(x=400,y=200,anchor="center")
        self.l11 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l11.place(x=400,y=300,anchor="center")
        self.l12 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l12.place(x=400,y=400,anchor="center")
        self.l13 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l13.place(x=500,y=200,anchor="center")
        self.l14 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l14.place(x=500,y=300,anchor="center")
        self.l15 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l15.place(x=500,y=400,anchor="center")
        self.l16 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l16.place(x=600,y=200,anchor="center")
        self.l17 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l17.place(x=600,y=300,anchor="center")
        self.l18 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l18.place(x=600,y=400,anchor="center")
        self.l19 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l19.place(x=700,y=200,anchor="center")
        self.l20 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l20.place(x=700,y=300,anchor="center")
        self.l21 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l21.place(x=700,y=400,anchor="center")
        self.l22 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l22.place(x=800,y=200,anchor="center")
        self.l23 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l23.place(x=800,y=300,anchor="center")
        self.l24 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l24.place(x=800,y=400,anchor="center")
        self.l25 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l25.place(x=900,y=200,anchor="center")
        self.l26 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l26.place(x=900,y=300,anchor="center")
        self.l27 = Label(self.game, width=11,height=5, bg= choice(self.warna))
        self.l27.place(x=900,y=400,anchor="center")
        self.mulai(self.a)

    def awal(self):
        self.gaming.pack_forget()
        self.masuk()

    def rubah(self,a,b):
        self.a = a
        self.b = b
        self.a["bg"] = "red"

        if a['bg'] != b['bg']:
            self.gagal()

    def mulai_easy(self):
        self.game.pack_forget()
        self.gaming = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.gaming.pack()
        self.secondEntry= Entry(self.gaming, width=3, font=("Helvetica",25,""),textvariable=self.second)
        self.secondEntry.place(x=500,y=30,anchor="center")
        self.judul = Label(self.gaming, text="Mudah",font='Helvetica 25 italic',bg="#F4DEB9").place(x=870,y=5)
        self.back = Button(self.gaming, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.awal).place(x=2,y=2)
        self.t1 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t1,self.l1))
        self.t1.place(x=400,y=200,anchor="center")
        self.t2 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t2,self.l2))
        self.t2.place(x=400,y=300,anchor="center")
        self.t3 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t3,self.l3))
        self.t3.place(x=400,y=400,anchor="center")
        self.t4 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t4,self.l4))
        self.t4.place(x=500,y=200,anchor="center")
        self.t5 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t5,self.l5))
        self.t5.place(x=500,y=300,anchor="center")
        self.t6 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t6,self.l6))
        self.t6.place(x=500,y=400,anchor="center")
        self.t7 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t7,self.l7))
        self.t7.place(x=600,y=200,anchor="center")
        self.t8 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t8,self.l8))
        self.t8.place(x=600,y=300,anchor="center")
        self.t9 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t9,self.l9))
        self.t9.place(x=600,y=400,anchor="center")

    def mulai_medium(self):
        self.game.pack_forget()
        self.gaming = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.gaming.pack()
        self.secondEntry= Entry(self.gaming, width=3, font=("Helvetica",25,""),textvariable=self.second)
        self.secondEntry.place(x=500,y=30,anchor="center")
        self.judul = Label(self.gaming, text="Sedang",font='Helvetica 25 italic',bg="#F4DEB9").place(x=870,y=5)
        self.back = Button(self.gaming, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.awal).place(x=2,y=2)
        self.t1 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t1,self.l1))
        self.t1.place(x=225,y=200,anchor="center")
        self.t2 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t2,self.l2))
        self.t2.place(x=225,y=300,anchor="center")
        self.t3 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t3,self.l3))
        self.t3.place(x=225,y=400,anchor="center")
        self.t4 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t4,self.l4))
        self.t4.place(x=325,y=200,anchor="center")
        self.t5 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t5,self.l5))
        self.t5.place(x=325,y=300,anchor="center")
        self.t6 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t6,self.l6))
        self.t6.place(x=325,y=400,anchor="center")
        self.t7 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t7,self.l7))
        self.t7.place(x=425,y=200,anchor="center")
        self.t8 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t8,self.l8))
        self.t8.place(x=425,y=300,anchor="center")
        self.t9 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t9,self.l9))
        self.t9.place(x=425,y=400,anchor="center")
        self.t10 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t10,self.l10))
        self.t10.place(x=525,y=200,anchor="center")
        self.t11 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t11,self.l11))
        self.t11.place(x=525,y=300,anchor="center")
        self.t12 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t12,self.l12))
        self.t12.place(x=525,y=400,anchor="center")
        self.t13 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t13,self.l13))
        self.t13.place(x=625,y=200,anchor="center")
        self.t14 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t14,self.l14))
        self.t14.place(x=625,y=300,anchor="center")
        self.t15 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t15,self.l15))
        self.t15.place(x=625,y=400,anchor="center")
        self.t16 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t16,self.l16))
        self.t16.place(x=725,y=200,anchor="center")
        self.t17 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t17,self.l17))
        self.t17.place(x=725,y=300,anchor="center")
        self.t18 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t18,self.l18))
        self.t18.place(x=725,y=400,anchor="center")

    def mulai_hard(self):
        self.game.pack_forget()
        self.gaming = Canvas(window, width=1000,height=600,bg="#F4DEB9")
        self.gaming.pack()
        self.secondEntry= Entry(self.gaming, width=3, font=("Helvetica",25,""),textvariable=self.second)
        self.secondEntry.place(x=500,y=30,anchor="center")
        self.judul = Label(self.gaming, text="Sulit",font='Helvetica 25 italic',bg="#F4DEB9").place(x=880,y=5)
        self.back = Button(self.gaming, bg="black",font='Helvetica 18 bold',borderwidth=0,width=10,text="Back",fg="#F4DEB9",command=self.awal).place(x=2,y=2)
        self.t1 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t1,self.l1))
        self.t1.place(x=100,y=200,anchor="center")
        self.t2 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t2,self.l2))
        self.t2.place(x=100,y=300,anchor="center")
        self.t3 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t3,self.l3))
        self.t3.place(x=100,y=400,anchor="center")
        self.t4 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t4,self.l4))
        self.t4.place(x=200,y=200,anchor="center")
        self.t5 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t5,self.l5))
        self.t5.place(x=200,y=300,anchor="center")
        self.t6 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t6,self.l6))
        self.t6.place(x=200,y=400,anchor="center")
        self.t7 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t7,self.l7))
        self.t7.place(x=300,y=200,anchor="center")
        self.t8 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t8,self.l8))
        self.t8.place(x=300,y=300,anchor="center")
        self.t9 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t9,self.l9))
        self.t9.place(x=300,y=400,anchor="center")
        self.t10 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t10,self.l10))
        self.t10.place(x=400,y=200,anchor="center")
        self.t11 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t11,self.l11))
        self.t11.place(x=400,y=300,anchor="center")
        self.t12 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t12,self.l12))
        self.t12.place(x=400,y=400,anchor="center")
        self.t13 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t13,self.l13))
        self.t13.place(x=500,y=200,anchor="center")
        self.t14 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t14,self.l14))
        self.t14.place(x=500,y=300,anchor="center")
        self.t15 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t15,self.l15))
        self.t15.place(x=500,y=400,anchor="center")
        self.t16 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t16,self.l16))
        self.t16.place(x=600,y=200,anchor="center")
        self.t17 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t17,self.l17))
        self.t17.place(x=600,y=300,anchor="center")
        self.t18 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t18,self.l18))
        self.t18.place(x=600,y=400,anchor="center")
        self.t19 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t19,self.l19))
        self.t19.place(x=700,y=200,anchor="center")
        self.t20 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t20,self.l20))
        self.t20.place(x=700,y=300,anchor="center")
        self.t21 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t21,self.l21))
        self.t21.place(x=700,y=400,anchor="center")
        self.t22 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t22,self.l22))
        self.t22.place(x=800,y=200,anchor="center")
        self.t23 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t23,self.l23))
        self.t23.place(x=800,y=300,anchor="center")
        self.t24 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t24,self.l24))
        self.t24.place(x=800,y=400,anchor="center")
        self.t25 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t25,self.l25))
        self.t25.place(x=900,y=200,anchor="center")
        self.t26 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t26,self.l26))
        self.t26.place(x=900,y=300,anchor="center")
        self.t27 =Button(self.gaming, width=11,height=5, bg = "black", borderwidth=0, command=lambda: self.rubah(self.t27,self.l27))
        self.t27.place(x=900,y=400,anchor="center")

    def mulai(self,a):
        self.second=StringVar()
        if a == "easy" :
            self.second.set("15")
        if a == "medium" :
            self.second.set("10")
        if a == "hard" :
            self.second.set("5")
        self.detik=StringVar()
        self.detik.set("2")
        self.secondEntry= Entry(self.game, width=3, font=("Helvetica",25,""),textvariable=self.second)
        self.secondEntry.place(x=500,y=30,anchor="center")
        cek = int(self.detik.get())
        while cek >=0:   
            mins,secs = divmod(cek,60)
            self.detik.set("{0:2d}".format(secs))
            window.update()
            time.sleep(1)
            if(cek == 0):
                temp =int(self.second.get())
                if a == "easy":
                    self.mulai_easy()
                elif a == "medium":
                    self.mulai_medium()
                else :
                    self.mulai_hard()
                while temp >=0:
                    mins,secs = divmod(temp,60)
                    self.second.set("{0:2d}".format(secs))
                    window.update()
                    time.sleep(1)
                    temp -= 1
                    if temp == 0 :
                        self.berhasil(a)
            cek -= 1
            

    def gagal(self):
        self.answer = messagebox.askretrycancel("Gagal", "Coba Lagi?") 
        if self.answer :
            self.gaming.pack_forget()
            self.masuk()
        else :
            window.destroy()

    def berhasil(self,a):
        if a == "easy":
            if self.l1['bg'] == self.t1['bg'] and self.l2['bg'] == self.t2['bg'] and self.l3['bg'] == self.t3['bg'] and self.l4['bg'] == self.t4['bg'] and self.l5['bg'] == self.t5['bg'] and self.l6['bg'] == self.t6['bg'] and self.l7['bg'] == self.t7['bg'] and self.l8['bg'] == self.t8['bg'] and self.l9['bg'] == self.t9['bg']:
                self.answer = messagebox.askretrycancel("Berhasil", "Coba Lagi?")
                if self.answer :
                    self.gaming.pack_forget() 
                    self.masuk()
                else :
                    window.destroy()
            else :
                self.gagal()
        elif a == "medium":
            if self.l1['bg'] == self.t1['bg'] and self.l2['bg'] == self.t2['bg'] and self.l3['bg'] == self.t3['bg'] and self.l4['bg'] == self.t4['bg'] and self.l5['bg'] == self.t5['bg'] and self.l6['bg'] == self.t6['bg'] and self.l7['bg'] == self.t7['bg'] and self.l8['bg'] == self.t8['bg'] and self.l9['bg'] == self.t9['bg'] and self.l10['bg'] == self.t10['bg'] and self.l11['bg'] == self.t11['bg'] and self.l12['bg'] == self.t12['bg'] and self.l13['bg'] == self.t13['bg'] and self.l14['bg'] == self.t14['bg'] and self.l15['bg'] == self.t15['bg'] and self.l16['bg'] == self.t16['bg'] and self.l17['bg'] == self.t17['bg'] and self.l18['bg'] == self.t18['bg']:
                self.answer = messagebox.askretrycancel("Berhasil", "Coba Lagi?")
                if self.answer :
                    self.gaming.pack_forget() 
                    self.masuk()
                else :
                    window.destroy()
            else :
                self.gagal()
        elif a == "hard":
            if self.l1['bg'] == self.t1['bg'] and self.l2['bg'] == self.t2['bg'] and self.l3['bg'] == self.t3['bg'] and self.l4['bg'] == self.t4['bg'] and self.l5['bg'] == self.t5['bg'] and self.l6['bg'] == self.t6['bg'] and self.l7['bg'] == self.t7['bg'] and self.l8['bg'] == self.t8['bg'] and self.l9['bg'] == self.t9['bg'] and self.l10['bg'] == self.t10['bg'] and self.l11['bg'] == self.t11['bg'] and self.l12['bg'] == self.t12['bg'] and self.l13['bg'] == self.t13['bg'] and self.l14['bg'] == self.t14['bg'] and self.l15['bg'] == self.t15['bg'] and self.l16['bg'] == self.t16['bg'] and self.l17['bg'] == self.t17['bg'] and self.l18['bg'] == self.t18['bg'] and self.l19['bg'] == self.t19['bg'] and self.l20['bg'] == self.t20['bg'] and self.l21['bg'] == self.t21['bg'] and self.l22['bg'] == self.t22['bg'] and self.l23['bg'] == self.t23['bg'] and self.l24['bg'] == self.t24['bg'] and self.l25['bg'] == self.t25['bg'] and self.l26['bg'] == self.t26['bg'] and self.l27['bg'] == self.t27['bg']:
                self.answer = messagebox.askretrycancel("Berhasil", "Coba Lagi?")
                if self.answer : 
                    self.masuk()
                else :
                    window.destroy()
            else :
                self.gagal()
menu = menu_utama()
menu.tampil_menu()
